### PR TITLE
Add sass

### PR DESCRIPTION
**Pull request by cnasikas**
Add gulp and sass. All files and layout changes are necessary in one commit so you can revert back to old stage immediately. If you thing I should break it in smaller commits let me know.

Depends on #1

### CODE REVIEW

**Comment by dionyziz** [comment]
Why is `css/bootstrap.css` included in this? Isn't this the output of SASS building?

**Comment by cnasikas** [comment]
Yes as main.css as well. I include them because there are still part of developing stage and for the moment are being called manually inside `index.html`.

The `dist` folder will be the build of the project and the `app.min.css` will contain the final css file with all styles. The same applys for js files. If you think we shouldn't include those files let me know.

**Comment by dionyziz** [comment]
I see you're using gulp, but the current recommendation is to use webpack with babel. For CSS, you can use the style-loader, css-loader and [sass-loader](https://github.com/webpack-contrib/sass-loader) in particular. What do you think?

**Review by dionyziz — CHANGES_REQUESTED** [review]
I see you're using gulp, but the current recommendation is to use webpack with babel. For CSS, you can use the style-loader, css-loader and [sass-loader](https://github.com/webpack-contrib/sass-loader) in particular. What do you think?

**Comment by cnasikas** [comment]
I thought webpack would be an overhead for a small project like this. Why not! It's an opportunity to learn webpack.

**Comment by cnasikas** [comment]
If we use webpack we have to decide the folder structure of the project. Would we have a `dist` folder or a `public` folder. Inside `src` folder we will have an `assets` folder for sass, images and fonts or not?

**Comment by dionyziz** [comment]
`dist` and `src` with `assets` sounds good!

**Pull request closed without merging**
